**16.2.2. Load trained model & make predictions**

In [1]:
# make sure the libraries are installed where these models are getting loaded
%pip install -q numpy pandas scikit-learn joblib

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

**Load joblib version**

In [2]:
import pandas as pd
from joblib import load

In [3]:
joblib_path = "D:\Machine learning Udemy\ML model deployment_9\Saving and loading_2\model_dir\diabetes_model_pipeline.joblib"

In [4]:
# load the saved model
loaded_joblib_pipeline = load(joblib_path)

In [5]:
# example new patient data
new_data = pd.DataFrame({
    "Pregnancies": [2],
    "Glucose": [120],
    "BloodPressure": [70],
    "SkinThickness": [25],
    "Insulin": [80],
    "BMI": [28.5],
    "DiabetesPedigreeFunction": [0.45],
    "Age": [35]
})

display(new_data)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,2,120,70,25,80,28.5,0.45,35

In [6]:
# data will be scaled and passed on to the model for prediction inside the pipeline
prediction = loaded_joblib_pipeline.predict(new_data)
print("Predicted class:", prediction[0])

if prediction[0] == 1:
    print("⚠️ Model predicts: Diabetes")
else:
    print("✅ Model predictes: No Diabetes")

Predicted class: 0
✅ Model predictes: No Diabetes

**Load pickle version**

In [7]:
import pandas as pd
import pickle

pickle_path = "D:\Machine learning Udemy\ML model deployment_9\Saving and loading_2\model_dir\diabetes_model_pipeline_pickle.pkl"

# load the trained pipeline using pickle
with open(pickle_path, "rb") as file:
    loaded_pickle_pipeline = pickle.load(file)

# example new patient data
new_data = pd.DataFrame({
    "Pregnancies": [2],
    "Glucose": [120],
    "BloodPressure": [70],
    "SkinThickness": [25],
    "Insulin": [80],
    "BMI": [28.5],
    "DiabetesPedigreeFunction": [0.45],
    "Age": [35]
})

display(new_data)

# data will be scaled and passed to the model automatically inside the pipeline
prediction = loaded_pickle_pipeline.predict(new_data)
print("Predicted class:", prediction[0])

if prediction[0] == 1:
    print("⚠️ Model predicts: Diabetes")
else:
    print("✅ Model predicts: No Diabetes")

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,2,120,70,25,80,28.5,0.45,35

Predicted class: 0
✅ Model predicts: No Diabetes

| Aspect | joblib | pickle |
|------|--------|--------|
| Speed (large models) | Fast | Slow |
| NumPy array handling | Optimized | Not optimized |
| Memory usage | Efficient | High |
| ML pipelines | Ideal | Works but suboptimal |
| Built-in | No | Yes |
| scikit-learn recommended | Yes | No |