**16.2.2. Load trained model**

These model files can be easily exported to another environment such as Google Colab, loaded there, and used to make predictions without retraining.

In [1]:
# make sure the libraries are installed where these models are getting loaded
# installing the required libraries
%pip install -q numpy pandas matplotlib scikit-learn joblib

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

**joblib version**

In [5]:
import pandas as pd
from joblib import load

In [3]:
joblib_path = "/Volumes/MyDrive/3_udemy/2_ml_course/udemy-2-ml-course-code-prep/section_16_ml_model_deployment/16_2_saving_and_loading_trained_models/model_dir/diabetes_model_pipeline.joblib"

In [ ]:
# loading the saved pipeline
loaded_joblib_pipeline = load(joblib_path)

In [6]:
# example new patient data
new_data = pd.DataFrame({
    "Pregnancies": [2],
    "Glucose": [120],
    "BloodPressure": [70],
    "SkinThickness": [25],
    "Insulin": [80],
    "BMI": [28.5],
    "DiabetesPedigreeFunction": [0.45],
    "Age": [35]
})

display(new_data)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,2,120,70,25,80,28.5,0.45,35

In [ ]:
# data will be scaled and passed on to the model inside the pipeline
prediction = loaded_joblib_pipeline.predict(new_data)
print("Predicted class:", prediction[0])

if prediction[0] == 1:
    print("⚠️ Model predicts: Diabetes")
else:
    print("✅ Model predicts: No Diabetes")

Predicted class: 0
✅ Model predicts: No Diabetes

**pickle version**

In [9]:
import pandas as pd
import pickle

pickle_path = "/Volumes/MyDrive/3_udemy/2_ml_course/udemy-2-ml-course-code-prep/section_16_ml_model_deployment/16_2_saving_and_loading_trained_models/model_dir/diabetes_model_pipeline.pkl"

# load the trained pipeline using pickle
with open(pickle_path, "rb") as file:
    loaded_pickle_pipeline = pickle.load(file)

# example new patient data
new_data = pd.DataFrame({
    "Pregnancies": [2],
    "Glucose": [120],
    "BloodPressure": [70],
    "SkinThickness": [25],
    "Insulin": [80],
    "BMI": [28.5],
    "DiabetesPedigreeFunction": [0.45],
    "Age": [35]
})

display(new_data)

# data will be scaled and passed to the model automatically inside the pipeline
prediction = loaded_pickle_pipeline.predict(new_data)
print("Predicted class:", prediction[0])

if prediction[0] == 1:
    print("⚠️ Model predicts: Diabetes")
else:
    print("✅ Model predicts: No Diabetes")

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,2,120,70,25,80,28.5,0.45,35

Predicted class: 0
✅ Model predicts: No Diabetes

| Aspect | joblib | pickle |
|------|--------|--------|
| Speed (large models) | Fast | Slow |
| NumPy array handling | Optimized | Not optimized |
| Memory usage | Efficient | High |
| ML pipelines | Ideal | Works but suboptimal |
| Built-in | No | Yes |
| scikit-learn recommended | Yes | No |
| Security | Unsafe for untrusted files | Unsafe for untrusted files |

>We will be using **joblib** for this course